import Header from "@/components/header/header";
import { UseFnProvider } from "@/context/cart-data-context";

import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <UseFnProvider>
          <Header />
          {children}
        </UseFnProvider>
      </body>
    </html>
  );
}
